version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
  postgres-data:
  pgadmin-data:
  cassandra-data:
  jupyter-data:
    driver: local

services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    restart: always
    ports:
      - 8889:8888
    volumes:
      - ./shared-workspace:/opt/workspace
      #- ./jupyter-data/notebooks:/opt/workspace/notebooks

  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 4041:4040
      - 18081:18080
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 4042:4040
      - 18082:18080
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 4043:4040
      - 18083:18080
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  postgres:
    image: postgres16
    container_name: postgres16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra-data:/var/lib/cassandra
